import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { signInWithPopup, GoogleAuthProvider, getAuth } from "firebase/auth";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();

  const auth = getAuth();

  const googleProvider = new GoogleAuthProvider();

  const handleLogin = async () => {
    try {
      const res = await signInWithPopup(auth, googleProvider);
      const idToken = await res.user.getIdToken();

      const login = await fetch("http://localhost:3000/api/login", {
        method: "POST",
        body: JSON.stringify({ idToken }),
      });
      await login.json();

      router.push("/home");
    } catch (error: any) {
      alert(error.message);
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Login</h1>
        <button type="button" onClick={handleLogin}>
          with google
        </button>
      </main>
    </div>
  );
};

export default Home;
